create table Edificio(
    id NUMBER(10,0) generated by default as identity, 
    nombre VARCHAR2 (255) not null,
    PRIMARY KEY (id),
    UNIQUE (nombre)
);

create table Piso(
    id NUMBER(10,0) generated by default as identity, 
    numeropiso INTEGER default 1 not null,
    idEdificio INTEGER not null,
    PRIMARY KEY (id),
    FOREIGN KEY (idEdificio) references Edificio,
    UNIQUE (numeropiso, idEdificio)
);

create table Cafeteria(
    id NUMBER(10,0) generated by default as identity, 
    nombre VARCHAR2 (255) not NULL,
    idPiso INTEGER not NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (idPiso)references Piso,
    UNIQUE (nombre)
    );
    
create table Colaborador (
    id NUMBER(10,0) generated by default as identity, 
    nombre VARCHAR2(255) not NULL,
    tipodocumento VARCHAR2(255) not NULL,
    numerodocumento INTEGER not NULL,
    vinculacion VARCHAR2(255) not NULL,
    check(vinculacion = 'PLANTA' or vinculacion = 'TEMPORAL'),
    comision INTEGER default 10 not NULL,
    PRIMARY KEY (id),
    check(comision between 0 and 100),
    UNIQUE (tipodocumento, numerodocumento)
    );
    
create table Meta(
    id NUMBER(10,0) generated by default as identity, 
    fechameta date not NULL,
    valormeta INTEGER default 0 not NULL,
    valorreal INTEGER default 0 not NULL,
    idCafeteria INTEGER not NULL,
    idColaborador INTEGER not NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (idColaborador) references Colaborador,
    FOREIGN KEY (idCafeteria) references Cafeteria,
    UNIQUE (idcolaborador, idcafeteria,fechameta)
    );



