GRANT SELECT ON edificio TO JPALACIO;
GRANT SELECT ON piso TO JPALACIO;
GRANT SELECT ON cafeteria TO JPALACIO;
GRANT SELECT ON colaborador TO JPALACIO;
GRANT SELECT ON meta TO JPALACIO;

GRANT SELECT ON VISTA_1 TO JPALACIO;
GRANT SELECT ON VISTA_2 TO JPALACIO;
GRANT SELECT ON VISTA_3 TO JPALACIO;
GRANT SELECT ON VISTA_4 TO JPALACIO;
GRANT SELECT ON VISTA_5 TO JPALACIO;
GRANT SELECT ON VISTA_6 TO JPALACIO;
GRANT SELECT ON VISTA_7 TO JPALACIO;
