-- Edificio: nombre is the natural key; the DBMS assigns the id.
INSERT INTO edificio (nombre) VALUES ('Instituto Pensar');
INSERT INTO edificio (nombre) VALUES ('Fernando Baron, S.J.');
INSERT INTO edificio (nombre) VALUES ('Gabriel Giraldo, S.J.');
INSERT INTO edificio (nombre) VALUES ('Talleres de Diseno Industrial');
INSERT INTO edificio (nombre) VALUES ('Lorenzo Uribe, S.J.');
INSERT INTO edificio (nombre) VALUES ('Atico');
INSERT INTO edificio (nombre) VALUES ('Julio Carrizosa');
INSERT INTO edificio (nombre) VALUES ('Jose Gabriel Maldonado, S.J.');
INSERT INTO edificio (nombre) VALUES ('Luis Felipe Silva Garavito');
INSERT INTO edificio (nombre) VALUES ('Centro de Educacion Continua');
INSERT INTO edificio (nombre) VALUES ('Leopoldo Rother');
INSERT INTO edificio (nombre) VALUES ('Carlos Arbelaez Camacho');
INSERT INTO edificio (nombre) VALUES ('Capilla Nuestra Senora del Camino');
INSERT INTO edificio (nombre) VALUES ('Talleres de Arquitectura');
INSERT INTO edificio (nombre) VALUES ('Jose Celestino Andrade, S.J.');
INSERT INTO edificio (nombre) VALUES ('Emilio Arango, S.J.');
INSERT INTO edificio (nombre) VALUES ('Cafeteria Central');
INSERT INTO edificio (nombre) VALUES ('Hospital Universitario San Ignacio');
INSERT INTO edificio (nombre) VALUES ('Facultad de Educacion');
INSERT INTO edificio (nombre) VALUES ('Facultad de Odontologia - Clinicas Odontologicas');
INSERT INTO edificio (nombre) VALUES ('Jose del Carmen Acosta');
INSERT INTO edificio (nombre) VALUES ('Jesus Maria Fernandez, S.J.');
INSERT INTO edificio (nombre) VALUES ('Nestor Santacoloma');
INSERT INTO edificio (nombre) VALUES ('Rafael Barrientos Conto, Morfologia');
INSERT INTO edificio (nombre) VALUES ('Instituto de Genetica Humana');
INSERT INTO edificio (nombre) VALUES ('Auditorio Alejandro Novoa, S.J.');
INSERT INTO edificio (nombre) VALUES ('Pablo VI');
INSERT INTO edificio (nombre) VALUES ('Facultad de Artes Ala Oriental');
INSERT INTO edificio (nombre) VALUES ('Salones Carrera de Estudios Musicales');
INSERT INTO edificio (nombre) VALUES ('Capilla San Francisco Javier');
INSERT INTO edificio (nombre) VALUES ('Cataluna');
INSERT INTO edificio (nombre) VALUES ('Quindio');
INSERT INTO edificio (nombre) VALUES ('Juniorado');
INSERT INTO edificio (nombre) VALUES ('Auditorio Felix Restrepo, S.J.');
INSERT INTO edificio (nombre) VALUES ('Felix Restrepo, S.J.');
INSERT INTO edificio (nombre) VALUES ('Angel Valtierra, S.J.');
INSERT INTO edificio (nombre) VALUES ('Carlos Ortiz, S.J.');
INSERT INTO edificio (nombre) VALUES ('Jesus Emilio Ramirez, S.J.');
INSERT INTO edificio (nombre) VALUES ('Instituto de Errores Innatos de Metabolismo');
INSERT INTO edificio (nombre) VALUES ('Bioterio');
INSERT INTO edificio (nombre) VALUES ('Jose Rafael Arboleda, S.J.');
INSERT INTO edificio (nombre) VALUES ('Centro Javeriano de Formacion Deportiva');
INSERT INTO edificio (nombre) VALUES ('Pedro Arrupe, S.J.');
INSERT INTO edificio (nombre) VALUES ('Manuel Briceno Jauregui, S.J.');
INSERT INTO edificio (nombre) VALUES ('Don Guillermo Castro');

COMMIT;
