INSERT INTO edificio (id, nombre) VALUES (1,   'Instituto Pensar');
INSERT INTO edificio (id, nombre) VALUES (2,   'Fernando Baron, S.J.');
INSERT INTO edificio (id, nombre) VALUES (3,   'Gabriel Giraldo, S.J.');
INSERT INTO edificio (id, nombre) VALUES (5,   'Talleres de Diseno Industrial');
INSERT INTO edificio (id, nombre) VALUES (7,   'Lorenzo Uribe, S.J.');
INSERT INTO edificio (id, nombre) VALUES (8,   'Atico');
INSERT INTO edificio (id, nombre) VALUES (9,   'Julio Carrizosa');
INSERT INTO edificio (id, nombre) VALUES (11,  'Jose Gabriel Maldonado, S.J.');
INSERT INTO edificio (id, nombre) VALUES (12,  'Luis Felipe Silva Garavito');
INSERT INTO edificio (id, nombre) VALUES (13,  'Centro de Educacion Continua');
INSERT INTO edificio (id, nombre) VALUES (15,  'Leopoldo Rother');
INSERT INTO edificio (id, nombre) VALUES (16,  'Carlos Arbelaez Camacho');
INSERT INTO edificio (id, nombre) VALUES (17,  'Capilla Nuestra Senora del Camino');
INSERT INTO edificio (id, nombre) VALUES (18,  'Talleres de Arquitectura');
INSERT INTO edificio (id, nombre) VALUES (19,  'Jose Celestino Andrade, S.J.');
INSERT INTO edificio (id, nombre) VALUES (21,  'Emilio Arango, S.J.');
INSERT INTO edificio (id, nombre) VALUES (23,  'Cafeteria Central');
INSERT INTO edificio (id, nombre) VALUES (24,  'Hospital Universitario San Ignacio');
INSERT INTO edificio (id, nombre) VALUES (25,  'Facultad de Educacion');
INSERT INTO edificio (id, nombre) VALUES (26,  'Facultad de Odontologia - Clinicas Odontologicas');
INSERT INTO edificio (id, nombre) VALUES (27,  'Jose del Carmen Acosta');
INSERT INTO edificio (id, nombre) VALUES (28,  'Jesus Maria Fernandez, S.J.');
INSERT INTO edificio (id, nombre) VALUES (30,  'Nestor Santacoloma');
INSERT INTO edificio (id, nombre) VALUES (31,  'Rafael Barrientos Conto, Morfologia');
INSERT INTO edificio (id, nombre) VALUES (32,  'Instituto de Genetica Humana');
INSERT INTO edificio (id, nombre) VALUES (34,  'Auditorio Alejandro Novoa, S.J.');
INSERT INTO edificio (id, nombre) VALUES (41,  'Pablo VI');
INSERT INTO edificio (id, nombre) VALUES (42,  'Facultad de Artes Ala Oriental');
INSERT INTO edificio (id, nombre) VALUES (44,  'Salones Carrera de Estudios Musicales');
INSERT INTO edificio (id, nombre) VALUES (45,  'Capilla San Francisco Javier');
INSERT INTO edificio (id, nombre) VALUES (46,  'Cataluna');
INSERT INTO edificio (id, nombre) VALUES (47,  'Quindio');
INSERT INTO edificio (id, nombre) VALUES (48,  'Juniorado');
INSERT INTO edificio (id, nombre) VALUES (49,  'Auditorio Felix Restrepo, S.J.');
INSERT INTO edificio (id, nombre) VALUES (50,  'Felix Restrepo, S.J.');
INSERT INTO edificio (id, nombre) VALUES (51,  'Angel Valtierra, S.J.');
INSERT INTO edificio (id, nombre) VALUES (52,  'Carlos Ortiz, S.J.');
INSERT INTO edificio (id, nombre) VALUES (53,  'Jesus Emilio Ramirez, S.J.');
INSERT INTO edificio (id, nombre) VALUES (54,  'Instituto de Errores Innatos de Metabolismo');
INSERT INTO edificio (id, nombre) VALUES (55,  'Bioterio');
INSERT INTO edificio (id, nombre) VALUES (67,  'Jose Rafael Arboleda, S.J.');
INSERT INTO edificio (id, nombre) VALUES (91,  'Centro Javeriano de Formacion Deportiva');
INSERT INTO edificio (id, nombre) VALUES (94,  'Pedro Arrupe, S.J.');
INSERT INTO edificio (id, nombre) VALUES (95,  'Manuel Briceno Jauregui, S.J.');
INSERT INTO edificio (id, nombre) VALUES (115, 'Don Guillermo Castro');

COMMIT;

